// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: docker_download.proto

package docker_downloadpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DockerDownload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
}

func (x *DockerDownload) Reset() {
	*x = DockerDownload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docker_download_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockerDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerDownload) ProtoMessage() {}

func (x *DockerDownload) ProtoReflect() protoreflect.Message {
	mi := &file_docker_download_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerDownload.ProtoReflect.Descriptor instead.
func (*DockerDownload) Descriptor() ([]byte, []int) {
	return file_docker_download_proto_rawDescGZIP(), []int{0}
}

func (x *DockerDownload) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type DockerDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DockerDownload *DockerDownload `protobuf:"bytes,1,opt,name=docker_download,json=dockerDownload,proto3" json:"docker_download,omitempty"`
}

func (x *DockerDownloadRequest) Reset() {
	*x = DockerDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docker_download_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockerDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerDownloadRequest) ProtoMessage() {}

func (x *DockerDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docker_download_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerDownloadRequest.ProtoReflect.Descriptor instead.
func (*DockerDownloadRequest) Descriptor() ([]byte, []int) {
	return file_docker_download_proto_rawDescGZIP(), []int{1}
}

func (x *DockerDownloadRequest) GetDockerDownload() *DockerDownload {
	if x != nil {
		return x.DockerDownload
	}
	return nil
}

type DockerDownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageFound bool   `protobuf:"varint,2,opt,name=image_found,json=imageFound,proto3" json:"image_found,omitempty"`
	ImageName  string `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	File       []byte `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *DockerDownloadResponse) Reset() {
	*x = DockerDownloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docker_download_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockerDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerDownloadResponse) ProtoMessage() {}

func (x *DockerDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docker_download_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerDownloadResponse.ProtoReflect.Descriptor instead.
func (*DockerDownloadResponse) Descriptor() ([]byte, []int) {
	return file_docker_download_proto_rawDescGZIP(), []int{2}
}

func (x *DockerDownloadResponse) GetImageFound() bool {
	if x != nil {
		return x.ImageFound
	}
	return false
}

func (x *DockerDownloadResponse) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *DockerDownloadResponse) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

var File_docker_download_proto protoreflect.FileDescriptor

var file_docker_download_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f,
	0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2f, 0x0a, 0x0e, 0x44, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x15, 0x44, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x48, 0x0a, 0x0f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x64, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x44, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x0e, 0x64, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x6c, 0x0a, 0x16,
	0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x32, 0x76, 0x0a, 0x15, 0x44, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x08, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x26, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x64, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_docker_download_proto_rawDescOnce sync.Once
	file_docker_download_proto_rawDescData = file_docker_download_proto_rawDesc
)

func file_docker_download_proto_rawDescGZIP() []byte {
	file_docker_download_proto_rawDescOnce.Do(func() {
		file_docker_download_proto_rawDescData = protoimpl.X.CompressGZIP(file_docker_download_proto_rawDescData)
	})
	return file_docker_download_proto_rawDescData
}

var file_docker_download_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_docker_download_proto_goTypes = []interface{}{
	(*DockerDownload)(nil),         // 0: docker_download.DockerDownload
	(*DockerDownloadRequest)(nil),  // 1: docker_download.DockerDownloadRequest
	(*DockerDownloadResponse)(nil), // 2: docker_download.DockerDownloadResponse
}
var file_docker_download_proto_depIdxs = []int32{
	0, // 0: docker_download.DockerDownloadRequest.docker_download:type_name -> docker_download.DockerDownload
	1, // 1: docker_download.DockerDownloadService.Download:input_type -> docker_download.DockerDownloadRequest
	2, // 2: docker_download.DockerDownloadService.Download:output_type -> docker_download.DockerDownloadResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_docker_download_proto_init() }
func file_docker_download_proto_init() {
	if File_docker_download_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_docker_download_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockerDownload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docker_download_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockerDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docker_download_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockerDownloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_docker_download_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docker_download_proto_goTypes,
		DependencyIndexes: file_docker_download_proto_depIdxs,
		MessageInfos:      file_docker_download_proto_msgTypes,
	}.Build()
	File_docker_download_proto = out.File
	file_docker_download_proto_rawDesc = nil
	file_docker_download_proto_goTypes = nil
	file_docker_download_proto_depIdxs = nil
}
