// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package docker_uploadpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DockerUploadServiceClient is the client API for DockerUploadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockerUploadServiceClient interface {
	Upload(ctx context.Context, in *DockerUploadRequest, opts ...grpc.CallOption) (*DockerUploadResponse, error)
}

type dockerUploadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerUploadServiceClient(cc grpc.ClientConnInterface) DockerUploadServiceClient {
	return &dockerUploadServiceClient{cc}
}

func (c *dockerUploadServiceClient) Upload(ctx context.Context, in *DockerUploadRequest, opts ...grpc.CallOption) (*DockerUploadResponse, error) {
	out := new(DockerUploadResponse)
	err := c.cc.Invoke(ctx, "/docker_uploadpb.DockerUploadService/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerUploadServiceServer is the server API for DockerUploadService service.
// All implementations must embed UnimplementedDockerUploadServiceServer
// for forward compatibility
type DockerUploadServiceServer interface {
	Upload(context.Context, *DockerUploadRequest) (*DockerUploadResponse, error)
	mustEmbedUnimplementedDockerUploadServiceServer()
}

// UnimplementedDockerUploadServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDockerUploadServiceServer struct {
}

func (UnimplementedDockerUploadServiceServer) Upload(context.Context, *DockerUploadRequest) (*DockerUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedDockerUploadServiceServer) mustEmbedUnimplementedDockerUploadServiceServer() {}

// UnsafeDockerUploadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerUploadServiceServer will
// result in compilation errors.
type UnsafeDockerUploadServiceServer interface {
	mustEmbedUnimplementedDockerUploadServiceServer()
}

func RegisterDockerUploadServiceServer(s grpc.ServiceRegistrar, srv DockerUploadServiceServer) {
	s.RegisterService(&DockerUploadService_ServiceDesc, srv)
}

func _DockerUploadService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerUploadServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/docker_uploadpb.DockerUploadService/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerUploadServiceServer).Upload(ctx, req.(*DockerUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DockerUploadService_ServiceDesc is the grpc.ServiceDesc for DockerUploadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerUploadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docker_uploadpb.DockerUploadService",
	HandlerType: (*DockerUploadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _DockerUploadService_Upload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docker_upload.proto",
}
